### PR TITLE
Relax bounds

### PR DESCRIPTION
**Pull request by TeofilC**
Everything compiles. But I couldn't run the doctests

### CODE REVIEW

**Comment by TeofilC** [comment]
Friendly ping @msakai . If you'd be willing to give me permissions, I would be happy to help with bumping version bounds

**Comment by msakai** [comment]
@TeofilC Thank you for the pull request and sorry for the late response. I'll take a look.

**Review by msakai — APPROVED** [review]
I also updated `package.yaml`.

**Comment by msakai** [comment]
I also relaxed the upper bounds of `decision-diagrams-0.2.0.0` on Hackage.

**Comment by TeofilC** [comment]
Thanks!

**Pull request merged**
